const cities = [
    { arabicName: "الدار البيضاء", englishName: "Casablanca" },
    { arabicName: "الرباط", englishName: "Rabat" },
    { arabicName: "طنجة", englishName: "Tangier" },
    { arabicName: "فاس", englishName: "Fez" },
    { arabicName: "مراكش", englishName: "Marrakech" },
    { arabicName: "أكادير", englishName: "Agadir" },
    { arabicName: "مكناس", englishName: "Meknes" },
    { arabicName: "العيون", englishName: "Laayoune" },
    { arabicName: "وجدة", englishName: "Oujda" },
    { arabicName: "كلميم", englishName: "Guelmim" },
    { arabicName: "المحمدية", englishName: "Mohammedia" },
    { arabicName: "أسفي", englishName: "Safi" },
    { arabicName: "القنيطرة", englishName: "Kenitra" },
    { arabicName: "طانطان", englishName: "Tan Tan" },
    { arabicName: "الحسيمة", englishName: "Al Hoceima" },
    { arabicName: "خريبكة", englishName: "Khouribga" },
    { arabicName: "الناظور", englishName: "Nador" },
    { arabicName: "سيدي قاسم", englishName: "Sidi Kacem" },
    { arabicName: "الجديدة", englishName: "El Jadida" },
    { arabicName: "تازة", englishName: "Taza" },
    { arabicName: "تطوان", englishName: "Tetouan" },
    { arabicName: "الفقيه بن صالح", englishName: "Fqih Ben Salah" },
    { arabicName: "تزنيت", englishName: "Tiznit" },
    { arabicName: "سلا", englishName: "Sale" },
    { arabicName: "ورزازات", englishName: "Ouarzazate" },
    { arabicName: "تاوريرت", englishName: "Taourirt" },
    { arabicName: "بركان", englishName: "Berkane" },
    { arabicName: "خنيفرة", englishName: "Khenifra" },
    { arabicName: "الرشيدية", englishName: "Errachidia" },
    { arabicName: "زاكورة", englishName: "Zagora" },
    { arabicName: "تمارة", englishName: "Temara" },
    { arabicName: "بني ملال", englishName: "Beni Mellal" },
    { arabicName: "سوق السبت", englishName: "Souq Larb'a al Gharb" },
    { arabicName: "سيدي بنور", englishName: "Sidi Bennour" },
    { arabicName: "تاونات", englishName: "Taounate" },
    { arabicName: "اليوسفية", englishName: "Youssoufia" },
    { arabicName: "الداخلة", englishName: "Dakhla" },
    { arabicName: "العرائش", englishName: "Al Hoceima" },
    { arabicName: "الفنيدق", englishName: "Fnideq" },
    { arabicName: "جرسيف", englishName: "Guercif" },
    { arabicName: "قلعة السراغنة", englishName: "Kelaat Sraghna" },
    { arabicName: "سيدي إفني", englishName: "Sidi Ifni" },
    { arabicName: "سيدي سليمان", englishName: "Sidi Slimane" },
    { arabicName: "القصر الكبير", englishName: "Ksar El Kebir" },
    { arabicName: "سيدي يوسف بن علي", englishName: "Sidi Yusuf ben Ali" },
    { arabicName: "تنغير", englishName: "Tinghir" },
    { arabicName: "المظيلة", englishName: "Midelt" },
    { arabicName: "قلعة الدكالة", englishName: "Kelaat Mgouna" },
    { arabicName: "ميدلت", englishName: "Midelt" },
    { arabicName: "الفجيج", englishName: "Foum El Oued" },
    { arabicName: "سيدي بنور", englishName: "Sidi Bennour" },
    { arabicName: "سيدي قاسم", englishName: "Sidi Kacem" },
    { arabicName: "العرائش", englishName: "Al Hoceima" },
    { arabicName: "واد زم", englishName: "Oued Zem" },
    { arabicName: "سبت الجديد", englishName: "Sebt Gzoula" },
    { arabicName: "جرادة", englishName: "Jerada" },
    { arabicName: "القصر الكبير", englishName: "Ksar El Kebir" },
    { arabicName: "سيدي بنور", englishName: "Sidi Bennour" },
    { arabicName: "سبت الجديد", englishName: "Sebt Gzoula" },
    { arabicName: "وادي زم", englishName: "Oued Zem" },
    { arabicName: "تيزنيت", englishName: "Tiznit" },
    { arabicName: "الراشدية", englishName: "Errachidia" },
    { arabicName: "خنيفرة", englishName: "Khenifra" },
    { arabicName: "مرتيل", englishName: "Martil" },
];